# Scrimmage against random heuristic
[match]
name = "random_scrim"
num_games = 10
time_control = "nodes 1"
start_fen = "startpos"

[ai1]
name = "naive"
path = "target/release/spooky"
[ai1.options]
heuristic = "naive"

[ai2]
name = "smart"
path = "target/release/spooky"
[ai2.options]
heuristic = "smart"
