# Scrimmage against random heuristic
[match]
name = "random_scrim"
num_games = 10
time_control = "nodes 1"
start_fen = "startpos"

[ai_yellow]
# The current development build (Naive by default)
path = "target/release/spooky"

[ai_blue]
# The current development build, but using random heuristic
path = "target/release/spooky"

[ai_blue.options]
heuristic = "random"
