# Scrimmage against random heuristic
[match]
name = "random_scrim"
num_games = 10
time_control = "nodes 1"
start_fen = "startpos"

[ai1]
name = "naive_dev"
path = "target/release/spooky"

[ai2]
name = "random_dev"
path = "target/release/spooky"
[ai2.options]
heuristic = "random"
