# Default configuration for AI vs AI scrimmages

[match]
# Name of the match configuration, used for naming output files.
name = "self_play"

# Number of games to play in the series.
num_games = 2

# Time control settings for each AI.
# Or "nodes <number>" or "movetime <ms>"
time_control = "nodes 1"

# Starting position in FEN format. "startpos" for the default setup.
start_fen = "startpos"

[ai1]
name = "spooky_v1"
path = "target/release/spooky"

[ai2]
name = "spooky_v2"
path = "target/release/spooky"
